### ISSUE TITLE
Reproducing paper results

### ISSUE THREAD

**Issue by alexrame** [DefangChen/OKDDip#1]
Hey, thanks for the reallly interesting work.
I am trying to reproduce your results from table 2 in your paper, concerning the branch-based accuracy on CIFAR100 with a resnet32.
You are supposed to have 25.65 +- 0.15 error rates, but with your current code I have 26.0 +- 0.3 accuracy, with 8 experiments.
Do you have any idea where the error might come from ?
Otherwise, I will have no other choice than to give this second value in my upcoming paper (where I plan to cite your reference as the current sota)
Thanks in advance

PS: Reproducing this in my own basecode what you're supposed to do gave me 25.9 +- 0.2.

**Comment by DefangChen** [comment]
Thanks for your feedback. Actually, I have received a message from an independent researcher that he just run these codes and found even better results. I guess these variance due to different runtime environment.
Beyond my expectation, I run these codes just now and also found better results (25.29). If you are interested, I can send you my training log. But I do not mind that you just report your reproducing results.

**Comment by alexrame** [comment]
Yes if you could send the tensorboard files, it would be really appreciated.
I am basically just running
`
python train_GL.py --model resnet32 --dataset CIFAR10
`

For information, I am able to reproduce (and even to improbe a little bit) the score for the ensembling in table 4, (which is not  fully implemented in the current repository), but not when I only keep the last branch in inference.

**Comment by DefangChen** [comment]
I have send the results to you, please check the email.
